# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    curl_http_adapter:
        class: Ivory\HttpAdapter\CurlHttpAdapter

    google_maps_geocoder:
        class: Geocoder\Provider\GoogleMaps
        arguments: ["@curl_http_adapter"]

    form_serializer:
        class: St0iK\FoodosBundle\Services\Utilities\FormErrorsSerializer
