<?php

namespace St0iK\FoodosBundle\Repository;

/**
 * ProductIngredientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductIngredientsRepository extends \Doctrine\ORM\EntityRepository
{
}
